# Connexion à PostgreSQL (Version Pro)
# L'URL finit par /ah_lp_builder_db car c'est le nom de la DB défini dans ton Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/ah_lp_builder_db
spring.datasource.username=ah_admin_lp
spring.datasource.password=AH_Secure_Vault_2026!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port du serveur
server.port=8080